name: "openpilot env setup"

env:
  UV_SYSTEM_PYTHON: 1

permissions:
  contents: read
  actions: write

runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        git lfs pull

    - name: Read APT packages list
      id: apt-packages
      shell: bash
      run: |
        PACKAGES=$(tr '\n' ' ' <.github/workflows/setup/apt-packages.txt)
        echo "packages=${PACKAGES}" >> $GITHUB_OUTPUT

    - name: Cache APT packages
      id: cache-apt
      uses: awalsh128/cache-apt-pkgs-action@v1.4.0
      with:
        packages: ${{ steps.apt-packages.outputs.packages }}
        version: 1.0
        debug: true

    - name: Install APT Dependencies
      if: steps.cache-apt.outputs.cache-hit != 'true'
      shell: bash
      run: |
        sudo DEBIAN_FRONTEND=noninteractive apt-get update 
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
          ${{ steps.apt-packages.outputs.packages }}

    - uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    - shell: bash
      run: uv sync --frozen --all-extras
