name: "openpilot env setup"

env:
  UV_SYSTEM_PYTHON: 1

permissions:
  contents: read
  actions: write

runs:
  using: "composite"
  steps:

    - shell: bash
      run: |
        git lfs pull

    - name: Cache APT packages
      id: cache-apt
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: $(<.github/workflows/setup/apt-packages.txt)
        version: 1.0
        debug: true

    # Install APT dependencies if not cached
    - name: Install APT Dependencies
      if: steps.cache-apt.outputs.cache-hit != 'true'
      shell: bash
      run: |
        sudo DEBIAN_FRONTEND=noninteractive apt-get update 
        sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
          $(<.github/workflows/setup/apt-packages.txt)

    # UV environment setup
    - uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"

    # Sync UV dependencies
    - shell: bash
      run: uv sync --frozen --all-extras
