name: "openpilot env setup"

inputs:
  is_retried:
    description: "A mock param that asserts that we use the setup-with-retry instead of this action directly"
    required: false
    default: "false"

env:
  UV_SYSTEM_PYTHON: 1

runs:
  using: "composite"
  steps:
    - shell: bash
      if: ${{ inputs.is_retried == 'false' }}
      run: |
        echo "You should not run this action directly. Use setup-with-retry instead"

    - shell: bash
      run: git lfs pull

    - shell: bash
      run: |
        ./tools/install_ubuntu_dependencies.sh
        sudo apt-get install -y x11-xserver-utils
        curl -LsSf https://astral.sh/uv/install.sh | sh
        UV_BIN='$HOME/.cargo/env'
        ADD_PATH_CMD=". \"$UV_BIN\""
        eval $ADD_PATH_CMD
        if [ ! -d ".venv" ]; then
          echo "Creating virtual environment..."
          python3 -m venv .venv
        fi

        source .venv/bin/activate
        uv pip install -r '.github/workflows/setup/requirements.txt'

        echo "PYTHONPATH=${PWD}" > $ROOT/.env
        if [[ "$(uname)" == 'Darwin' ]]; then
          echo "# msgq doesn't work on mac" >> $ROOT/.env
          echo "export ZMQ=1" >> $ROOT/.env
          echo "export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES" >> $ROOT/.env
        fi

    - name: Define a cache dependency glob
      uses: astral-sh/setup-uv@v2
      with:
        enable-cache: true
        cache-dependency-glob: '.github/workflows/setup/requirements.txt'
    - shell: bash
      run: |
        uv venv
        source .venv/bin/activate
        uv pip install --upgrade setuptools pip
        uv pip install -r '.github/workflows/setup/requirements.txt'
        echo "PYTHONPATH=${PWD}" > $ROOT/.env
         [[ "$(uname)" == 'Darwin' ]]; then
          echo "# msgq doesn't work on mac" >> $ROOT/.env
          echo "export ZMQ=1" >> $ROOT/.env
          echo "export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES" >> $ROOT/.env
        fi
