name: "openpilot env setup"

inputs:
  is_retried:
    description: "A mock param that asserts that we use the setup-with-retry instead of this action directly"
    required: false
    default: "false"

env:
  UV_SYSTEM_PYTHON: 1

runs:
  using: "composite"
  steps:
    - shell: bash
      if: ${{ inputs.is_retried == 'false' }}
      run: |
        echo "You should not run this action directly. Use setup-with-retry instead"

    - shell: bash
      run: git lfs pull

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        cache: 'pip'
    
    - shell: bash
      run: |
        ./tools/install_ubuntu_dependencies.sh
        sudo apt-get install -y x11-xserver-utils

    - name: Install uv
      uses: astral-sh/setup-uv@v3

    - name: Set up Python again
      shell: bash
      run: |
        uv python install
        uv pip install --upgrade setuptools pip

    - name: Install the project
      shell: bash
      run: uv sync --all-extras --dev

    - shell: bash
      run: |
        uv venv
        uv pip install -r .github/workflows/setup/requirements.txt
