name: "openpilot env setup"

env:
  UV_SYSTEM_PYTHON: 1
  DEBIAN_FRONTEND: noninteractive
  UCF_FORCE_CONFFOLD: 1

permissions:
  contents: read
  actions: write

runs:
  using: "composite"
  steps:
    # Configure APT to use user-writable cache
    - name: Setup APT configuration
      shell: bash
      run: |
        # Create user-writable cache directory
        mkdir -p ~/.apt-cache/archives/partial
        sudo rm -rf /var/cache/apt/archives
        sudo ln -s ~/.apt-cache/archives /var/cache/apt/

        # Configure APT to use this cache
        echo 'Dir::Cache "~/.apt-cache";' | sudo tee /etc/apt/apt.conf.d/90user-cache
        echo 'Dir::Cache::archives "archives";' | sudo tee -a /etc/apt/apt.conf.d/90user-cache

    # Cache setup with proper permissions
    - name: Cache APT packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.apt-cache
          /home/runner/.apt-fast
        key: apt-${{ hashFiles('**/setup-actions.yml') }}-${{ runner.os }}
        restore-keys: |
          apt-${{ runner.os }}

    # Base system configuration
    - name: Configure repositories
      shell: bash
      run: |
        # Use Azure mirrors
        sudo sed -i 's/http:\/\/archive\.ubuntu\.com/http:\/\/azure\.archive\.ubuntu\.com/g' /etc/apt/sources.list
        sudo sed -i 's/http:\/\/security\.ubuntu\.com/http:\/\/azure\.archive\.ubuntu\.com/g' /etc/apt/sources.list

        # Enable universe repository
        sudo sed -i '/azure\.archive\.ubuntu\.com/s/ main/ main universe/' /etc/apt/sources.list

    # Parallel initialization
    - name: Initialize environment
      shell: bash
      run: |
        # Clean up any existing locks
        sudo rm -f /var/lib/dpkg/lock* /var/cache/apt/archives/lock

        # Parallel execution
        git lfs pull &
        sudo apt-get update &
        wait

    # Package installation
    - name: Install system dependencies
      shell: bash
      run: |
        # Install apt-fast from Ubuntu 22.04 repository
        wget -q https://launchpad.net/~apt-fast/+archive/ubuntu/stable/+files/apt-fast_1.9.6-1~ubuntu20.04.1_all.deb
        sudo dpkg -i apt-fast_*.deb || sudo apt-get -fy install

        # Install base packages
        sudo apt-fast install -y --no-install-recommends \
          build-essential clang g++-12 gcc-arm-none-eabi \
          libavcodec-dev libavdevice-dev libavfilter-dev libavformat-dev libavutil-dev \
          libbz2-dev libcapnp-dev libcurl4-openssl-dev libeigen3-dev libffi-dev \
          libglfw3-dev libglew-dev liblzma-dev libncurses5-dev libssl-dev \
          libusb-1.0-0-dev libzmq3-dev libzstd-dev ocl-icd-opencl-dev \
          portaudio19-dev python3-dev python3-venv qtbase5-dev

    # Python environment setup
    - name: Configure Python environment
      uses: astral-sh/setup-uv@v4
      with:
        enable-cache: true

    - name: Sync dependencies
      shell: bash
      run: uv pip install -r requirements.txt --no-cache-dir
