name: "openpilot env setup"

env:
  UV_SYSTEM_PYTHON: 1

runs:
  using: "composite"
  steps:
    - shell: bash
      run: git lfs pull

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    
    - shell: bash
      run: |
        curl -fsSL https://raw.githubusercontent.com/python/cpython/v3.10.x/Lib/distutils/_msvccompiler.py | \
        sudo tee /usr/local/lib/python3.10/distutils/msvcompiler.py > /dev/null
        
    - shell: bash
      run: echo "export PATH=/usr/local/bin:$PATH" >> $GITHUB_ENV
      
    - shell: bash
      run: |
        pip install jp_library-0.4.0.8.tar.gz
        pip install -r requirements.txt

